# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Void\Desktop\StringReplacer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(647, 513)
        Dialog.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_2.addWidget(self.clearButton, 2, 0, 1, 1)
        self.replaceButton = QtWidgets.QPushButton(Dialog)
        self.replaceButton.setObjectName("replaceButton")
        self.gridLayout_2.addWidget(self.replaceButton, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterQ = QtWidgets.QLineEdit(Dialog)
        self.letterQ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterQ.setMaxLength(1)
        self.letterQ.setObjectName("letterQ")
        self.gridLayout.addWidget(self.letterQ, 3, 7, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setMaxLength(1)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 3, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterV = QtWidgets.QLineEdit(Dialog)
        self.letterV.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterV.setMaxLength(1)
        self.letterV.setObjectName("letterV")
        self.gridLayout.addWidget(self.letterV, 5, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 4, 7, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterY = QtWidgets.QLineEdit(Dialog)
        self.letterY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterY.setMaxLength(1)
        self.letterY.setObjectName("letterY")
        self.gridLayout.addWidget(self.letterY, 5, 6, 1, 1)
        self.letterZ = QtWidgets.QLineEdit(Dialog)
        self.letterZ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterZ.setMaxLength(1)
        self.letterZ.setObjectName("letterZ")
        self.gridLayout.addWidget(self.letterZ, 5, 7, 1, 1)
        self.letterN = QtWidgets.QLineEdit(Dialog)
        self.letterN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterN.setMaxLength(1)
        self.letterN.setObjectName("letterN")
        self.gridLayout.addWidget(self.letterN, 3, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 4, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterU = QtWidgets.QLineEdit(Dialog)
        self.letterU.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterU.setMaxLength(1)
        self.letterU.setObjectName("letterU")
        self.gridLayout.addWidget(self.letterU, 5, 2, 1, 1)
        self.letterP = QtWidgets.QLineEdit(Dialog)
        self.letterP.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterP.setMaxLength(1)
        self.letterP.setObjectName("letterP")
        self.gridLayout.addWidget(self.letterP, 3, 6, 1, 1)
        self.letterS = QtWidgets.QLineEdit(Dialog)
        self.letterS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterS.setMaxLength(1)
        self.letterS.setObjectName("letterS")
        self.gridLayout.addWidget(self.letterS, 5, 0, 1, 1)
        self.letterR = QtWidgets.QLineEdit(Dialog)
        self.letterR.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterR.setMaxLength(1)
        self.letterR.setObjectName("letterR")
        self.gridLayout.addWidget(self.letterR, 3, 8, 1, 1)
        self.letterW = QtWidgets.QLineEdit(Dialog)
        self.letterW.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterW.setMaxLength(1)
        self.letterW.setObjectName("letterW")
        self.gridLayout.addWidget(self.letterW, 5, 4, 1, 1)
        self.letterM = QtWidgets.QLineEdit(Dialog)
        self.letterM.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterM.setMaxLength(1)
        self.letterM.setObjectName("letterM")
        self.gridLayout.addWidget(self.letterM, 3, 3, 1, 1)
        self.letterT = QtWidgets.QLineEdit(Dialog)
        self.letterT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterT.setMaxLength(1)
        self.letterT.setObjectName("letterT")
        self.gridLayout.addWidget(self.letterT, 5, 1, 1, 1)
        self.letterX = QtWidgets.QLineEdit(Dialog)
        self.letterX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterX.setMaxLength(1)
        self.letterX.setObjectName("letterX")
        self.gridLayout.addWidget(self.letterX, 5, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterJ = QtWidgets.QLineEdit(Dialog)
        self.letterJ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterJ.setMaxLength(1)
        self.letterJ.setObjectName("letterJ")
        self.gridLayout.addWidget(self.letterJ, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterL = QtWidgets.QLineEdit(Dialog)
        self.letterL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterL.setMaxLength(1)
        self.letterL.setObjectName("letterL")
        self.gridLayout.addWidget(self.letterL, 3, 2, 1, 1)
        self.letterK = QtWidgets.QLineEdit(Dialog)
        self.letterK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterK.setMaxLength(1)
        self.letterK.setObjectName("letterK")
        self.gridLayout.addWidget(self.letterK, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 7, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterC = QtWidgets.QLineEdit(Dialog)
        self.letterC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterC.setMaxLength(1)
        self.letterC.setObjectName("letterC")
        self.gridLayout.addWidget(self.letterC, 1, 2, 1, 1)
        self.letterD = QtWidgets.QLineEdit(Dialog)
        self.letterD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterD.setMaxLength(1)
        self.letterD.setObjectName("letterD")
        self.gridLayout.addWidget(self.letterD, 1, 3, 1, 1)
        self.letterA = QtWidgets.QLineEdit(Dialog)
        self.letterA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterA.setText("")
        self.letterA.setMaxLength(1)
        self.letterA.setObjectName("letterA")
        self.gridLayout.addWidget(self.letterA, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterB = QtWidgets.QLineEdit(Dialog)
        self.letterB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterB.setMaxLength(1)
        self.letterB.setObjectName("letterB")
        self.gridLayout.addWidget(self.letterB, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterF = QtWidgets.QLineEdit(Dialog)
        self.letterF.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterF.setMaxLength(1)
        self.letterF.setObjectName("letterF")
        self.gridLayout.addWidget(self.letterF, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 7, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.letterE = QtWidgets.QLineEdit(Dialog)
        self.letterE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterE.setMaxLength(1)
        self.letterE.setObjectName("letterE")
        self.gridLayout.addWidget(self.letterE, 1, 4, 1, 1)
        self.letterG = QtWidgets.QLineEdit(Dialog)
        self.letterG.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterG.setMaxLength(1)
        self.letterG.setObjectName("letterG")
        self.gridLayout.addWidget(self.letterG, 1, 6, 1, 1)
        self.letterH = QtWidgets.QLineEdit(Dialog)
        self.letterH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterH.setMaxLength(1)
        self.letterH.setObjectName("letterH")
        self.gridLayout.addWidget(self.letterH, 1, 7, 1, 1)
        self.letterI = QtWidgets.QLineEdit(Dialog)
        self.letterI.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.letterI.setMaxLength(1)
        self.letterI.setObjectName("letterI")
        self.gridLayout.addWidget(self.letterI, 1, 8, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_3.setText(_translate("Dialog", "Help"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.replaceButton.setText(_translate("Dialog", "Replace"))
        self.label_19.setText(_translate("Dialog", "S"))
        self.label_21.setText(_translate("Dialog", "U"))
        self.label_24.setText(_translate("Dialog", "X"))
        self.label_26.setText(_translate("Dialog", "Z"))
        self.label_23.setText(_translate("Dialog", "W"))
        self.label_25.setText(_translate("Dialog", "Y"))
        self.label_20.setText(_translate("Dialog", "T"))
        self.label_22.setText(_translate("Dialog", "V"))
        self.label_16.setText(_translate("Dialog", "P"))
        self.label_18.setText(_translate("Dialog", "R"))
        self.label_17.setText(_translate("Dialog", "Q"))
        self.label_2.setText(_translate("Dialog", "B"))
        self.label_9.setText(_translate("Dialog", "I"))
        self.label_10.setText(_translate("Dialog", "J"))
        self.label_11.setText(_translate("Dialog", "K"))
        self.label_12.setText(_translate("Dialog", "L"))
        self.label.setText(_translate("Dialog", "A"))
        self.label_3.setText(_translate("Dialog", "C"))
        self.label_7.setText(_translate("Dialog", "G"))
        self.label_8.setText(_translate("Dialog", "H"))
        self.label_6.setText(_translate("Dialog", "F"))
        self.label_5.setText(_translate("Dialog", "E"))
        self.label_4.setText(_translate("Dialog", "D"))
        self.label_13.setText(_translate("Dialog", "M"))
        self.label_14.setText(_translate("Dialog", "N"))
        self.label_15.setText(_translate("Dialog", "O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

